### PR TITLE
fix warnings on state.when; try to add centos8; change vagrant boxes …

### PR DESCRIPTION
**Pull request by mkinney**
…to ones that have both vagrant and vmware

Let me know if you want to change anything.

It feels like we should have something like:

```
server.shell(
    {'Run simple docker hello'},
    'echo "docker run --rm hello-world"',
)
```

at the end to verify/validate docker works as expected or something. Maybe?

### CODE REVIEW

**Comment by mkinney** [comment]
Interesting. Looks like others suggest using the `--nobest` option.  (see https://www.linuxtechi.com/install-docker-ce-centos-8-rhel-8/ for example)

```
# yum install --help | grep nobest
                   [--skip-broken] [-h] [--allowerasing] [-b | --nobest] [-C]
  --nobest              do not limit the transaction to the best candidate
```

How do you add an additional argument to yum?

The docs do not show any args:
`yum.packages(packages=None, present=True, latest=False, update=False, clean=False)`

**Comment by mkinney** [comment]
Looks like you could add `installArgs=''` to https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/modules/yum.py#L145

then change:
https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/modules/yum.py#L168 to something like:
`        install_command='yum install -y' + installArgs,`

Might as well add `uninstallArgs` and `upgradeArgs` too.

I could open and issue and do a PR if you're open to something like that.

**Comment by mkinney** [comment]
Oh, and

` ls -al /usr/bin/yum
lrwxrwxrwx. 1 root root 5 May 13  2019
/usr/bin/yum -> dnf-3
`

So, it might be good to update the pyinfra that it "supports" dnf, too. (as it is the new and shiny yum)

Need your help on how to update the doc for this. Do you want to "duplicate" the documentation or just refer both?

**Comment by mkinney** [comment]
Created https://github.com/Fizzadar/pyinfra/pull/192

**Review by Fizzadar — APPROVED** [review]
This looks good so far - pending pyinfra updates!

**Review by Fizzadar — APPROVED** [review]
I never got around to merging this, apologies @mkinney!

**Pull request merged**
